[project]
name = "releasy_lib"
version = "5.0.0-alpha.1"
description = "A library to mine release data"
authors = [{ name = "Felipe Curty", email = "felipecrp@gmail.com" }]
requires-python = ">=3.12, <4"
readme = "README.md"
license = "MIT"
dependencies = [
    "pygit2>=1.17.0,<2",
    "pyyaml>=6.0.2,<7",
    "python-dateutil>=2.9.0,<3",
]

[project.urls]
Repository = "https://github.com/gems-uff/releasy"

[dependency-groups]
dev = [
    "pylint>=4.0.0,<5",
    "pytest>=9,<10",
    "pytest-cov>=7.0.0,<8",
    "pytest-profiling>=1.8.1,<2",
    "pytest-pyspec>=1.0.0,<2",
]

[tool.hatch.build.targets.sdist]
include = ["src/releasy"]

[tool.hatch.build.targets.wheel]
include = ["src/releasy"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
addopts = "--pyspec --ignore=tests/old"
pythonpath = ["src"]
